### ISSUE TITLE
Repositoryk és controllerek hozzáadása

### ISSUE THREAD

**Issue by adamszkimarci** [adamszkimarci/szobaeloszto#2]
Repositoryk és controllerek hozzáadása az alábbi Entitykhez:

- User

- Diak

- Szoba

- Epulet

- Beosztas

**Comment by kapy96** [comment]
A feature-repos-and-controllers branchen commitoltam, létrehoztam egy pull requestet nézzétek át, ha jó, akkor fogadjátok el.
