### ISSUE TITLE
Létrehozni a Userhez szükséges osztályokat

### ISSUE THREAD

**Issue by adamszkimarci** [adamszkimarci/szobaeloszto#4]
Megjegyzés: a User osztály az loginban fog szerepet játszani, a Diák osztály pedig maga beosztás megvalósítását fogja segíteni.

- [x] User entity létrehozása

- [x] User repository létrehozása

- [x] User controller létrehozása

**Comment by ghost** [comment]
Elkészült a user osztály, a securityvel együtt fog működni.
